### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by rbello** [m-creations/docker-fusiondirectory-ldap#1]
Hi,
I just installed both docker container "docker-fusiondirectory-ldap" and "docker-fusiondirectory", they are connected together, but how to login to FusionDirectory ? I tried several options for the username ("root", "admin", "Manager", ...) and i used the password given to "docker run -e LDAP_ROOTPW". 
Regards,

**Comment by rezarahimi** [comment]
Hi,
The admin user for Fusiondirectory is **fd-admin**, so please try using fd-admin with the given LDAP_ROOTPW password.
Regards

**Comment by darabi** [comment]
I first thought we might need to add some documentation, but the README at https://github.com/m-creations/docker-fusiondirectory already states:

> Now open http://localhost:12080 and login as fd-admin using LDAP_ROOTPW as password.

So closing this.
